# Generated by Django 5.2.4 on 2025-07-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balcony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balcony_direction', models.CharField(choices=[('south', 'South facing'), ('north', 'North facing'), ('east', 'East facing'), ('west', 'West facing')], default='south', max_length=10)),
                ('balcony_size', models.FloatField(help_text='Size in square meters')),
            ],
        ),
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('usda_zone', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], null=True)),
                ('average_sunshine_hours', models.FloatField(blank=True, null=True)),
                ('average_cloud_cover', models.FloatField(blank=True, null=True)),
                ('average_rainfall', models.FloatField(blank=True, null=True)),
                ('average_wind', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sunlight_min', models.FloatField(blank=True, null=True)),
                ('sunlight_max', models.FloatField(blank=True, null=True)),
                ('usda_min', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], null=True)),
                ('usda_max', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], null=True)),
                ('water_need', models.CharField(blank=True, choices=[('dry', 'Low'), ('moist', 'Medium'), ('wet', 'High')], max_length=20, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('shade', models.CharField(blank=True, choices=[('full', 'Full shade'), ('partial', 'Partial shade'), ('toleration', 'Tolerates partial shade'), ('full_sun', 'Full sun')], max_length=20, null=True)),
                ('category', models.CharField(blank=True, choices=[('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('herb', 'Herb'), ('flower', 'Flower')], max_length=20, null=True)),
                ('wind', models.CharField(blank=True, choices=[('low', 'Low winds'), ('medium', 'Medium winds'), ('high', 'Strong winds'), ('very_high', 'Very strong winds')], max_length=20, null=True)),
            ],
        ),
    ]
