# Generated by Django 5.2.4 on 2025-08-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plants_category_alter_plants_shade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climatedata',
            old_name='average_sunshine_hours',
            new_name='average_sunshine_hours_aug',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='average_cloud_cover',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='average_rainfall',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='average_wind',
        ),
        migrations.AddField(
            model_name='climatedata',
            name='average_sunshine_hours_apr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climatedata',
            name='average_sunshine_hours_dec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climatedata',
            name='average_sunshine_hours_feb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climatedata',
            name='average_sunshine_hours_jan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climatedata',
            name='average_sunshine_hours_jul',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climatedata',
            name='average_sunshine_hours_jun',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climatedata',
            name='average_sunshine_hours_mar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climatedata',
            name='average_sunshine_hours_may',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climatedata',
            name='average_sunshine_hours_nov',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climatedata',
            name='average_sunshine_hours_oct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climatedata',
            name='average_sunshine_hours_sep',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
