# Generated by Django 5.2.4 on 2025-08-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_rename_average_sunshine_hours_climatedata_average_sunshine_hours_aug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='usda_zone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='usda_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='usda_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
