# Generated by Django 5.2.4 on 2025-08-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_cities_alter_climatedata_usda_zone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='shade',
        ),
    ]
