# Generated by Django 5.2.4 on 2025-08-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_remove_plants_shade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='category',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='height',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='sunlight_max',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='sunlight_min',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='usda_max',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='usda_min',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='water_need',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='width',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='wind',
        ),
    ]
