# Generated by Django 5.2.4 on 2025-08-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_remove_plants_category_remove_plants_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='sunlight_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='sunlight_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='usda_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='usda_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='water_need',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='wind',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
