# Generated by Django 5.2.4 on 2025-08-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_plants_category_plants_height_plants_sunlight_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='shade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
